---
environment_path: ".sandbox/F0OAd-RcKjOxgm8Od3mQL"
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: ".sandbox/F0OAd-RcKjOxgm8Od3mQL/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 9000
network: ~
